[package]
name = "strobe-rs"
repository = "https://github.com/rozbb/strobe-rs"
documentation = "https://docs.rs/strobe-rs"
description = "An implementation of the Strobe protocol framework in pure Rust"
version = "0.4.0"
edition = "2018"
authors = ["Michael Rosenberg <micro@fastmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["crypto", "strobe", "protocol", "framework", "no_std"]

[features]
default = ["std"]
std = ["subtle/std"]
nightly = ["subtle/nightly"]

# Setting the appropriate flags so these are all no_std

[dependencies]
bitflags = "1.0"
byteorder = { version = "1.2", default-features = false } # Don't need the std stuff at all
tiny-keccak = "1.0"

[dependencies.subtle]
version = "0.6"
default-features = false
features = ["generic-impls"] # Defaults are ["std, generic-impls"]

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.3"
